### ISSUE TITLE
Attempt to get length of local 'iptable' (a nil value)

### ISSUE THREAD

**Issue by MorrisonWill** [jbyuki/instant.nvim#14]
I installed instant.nvim in my lunarvim config and set instant_username. Trying to connect to the server started from InstantStartServer, I get the following error:

E5108: Error executing lua ...cker/start/instant.nvim/lua/instant/websocket_client.lua:60: attempt to get length of local 'iptable' (a nil value)

What can I do to fix this?

**Comment by ohmree** [comment]
I also got this error when trying to connect to a properly-configured instance hosted on heroku, so I fiddled a bit with `vim.loop.getaddrinfo` and found out what the issue was - I was adding `https://` to my deployed app's url when I should've just used `myappname.herokuapp.com`.

You might want to either add a fix for this or mention it in the docs as I don't see it mentioned anywhere.

**Comment by jbyuki** [comment]
It's mentioned here (for ngrok in this case) : https://github.com/jbyuki/instant.nvim/wiki/Deploy-a-server#connect-remote-client

**Comment by ohmree** [comment]
> It's mentioned here (for ngrok in this case) : https://github.com/jbyuki/instant.nvim/wiki/Deploy-a-server#connect-remote-client

Ah, I see. Fair enough then.
If anyone is like me and only skims through the bits that they deem relevant to their use case then at least they'll be able to find my comment now.

**Comment by kj-jondell** [comment]
Hello, having problem connecting to another host on the same LAN. Getting either this (iptable nil value) or ECONNREFUSED (similar to 
 https://github.com/jbyuki/instant.nvim/issues/8). Works locally with 127.0.0.1 but not remotely on the same network. Both client and server are MacOS.
